// Copyright (c) 2021 - 2022 Buijs Software
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import "dart:convert";

import "package:squint/squint.dart";

/// Example DTO as defined by the user.
@squint
class ExampleResponse {
  /// Constructor!
  ExampleResponse({
    required this.count,
    required this.name,
  });

  final int count;
  final String name;

}

/// Example extension to (de)serialize as generated by the squint library.
ExampleResponse deserializeExampleResponse(String json) =>
    deserializeExampleResponseMap(jsonDecode(json) as Map<String, dynamic>);

ExampleResponse deserializeExampleResponseMap(Map<String, dynamic> data) =>
    ExampleResponse(
      count: data.intValueOrThrow(key: "count"),
      name: data.stringValueOrThrow(key: "name"),
    );

void main() {

  const x = """
  {
    "count": 2,
    "name": "squint!"
  }""";

  final response = deserializeExampleResponse(x);
  print("Count is ${response.count}"); // Prints: Count is 2.
  print("Name is ${response.name}"); // Prints: Name is squint!.
}