name: squint_json
description: Lightweight JSON processor and AST. Safely (de)serialize JSON decoded Strings to Dart Types.
version: 0.1.3
homepage: https://buijs.dev
repository: https://github.com/buijs-dev/squint

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  analyzer: ^6.3.0
  dart_style: ^2.3.3
  path: ^1.8.1

dev_dependencies:
  coverage: ^1.6.4
  dartdoc: ^7.0.0
  lints: ^2.1.1
  test: ^1.16.0