name: squint
description: Lightweight JSON processing code generator. Safely deserialize JSON decoded Strings to Dart Types.
version: 0.0.1
homepage: https://buijs.dev
repository: https://github.com/buijs-dev/squint

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^5.2.0

dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7
  coverage: ^1.3.2
  dartdoc: ^6.1.0
  lints: ^2.0.0
  test: ^1.16.0
